"""Collect the saved evidence into evidence/SUMMARY.md (numbers come only from saved run files).

    python scripts/summarize_evidence.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
import sys
EVID = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "evidence"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    lines = ["# Evidence summary", "",
             "_Generated by `python scripts/summarize_evidence.py` from the JSON files in this folder. "
             "No number here is typed by hand._", ""]

    cards = sorted((EVID / "ask").glob("test-*.json"))
    if cards:
        env = load(cards[0])["environment"]
        m = env["model"]
        lines += ["## Model and run", "", "| | |", "|---|---|",
                  f"| Model | `{m.get('model')}` ({m.get('family')}, {m.get('parameter_size')}, {m.get('quantization')}, "
                  f"{m.get('file_size_gb')} GB file, digest `{str(m.get('digest'))[:12]}`) |",
                  f"| Runtime | Ollama {m.get('runtime_version')} |",
                  f"| Internet reachable during eval | {env['internet_reachable']} |",
                  f"| Loaded model memory (Ollama `/api/ps`) | " + ", ".join(
                      f"{x['loaded_size_gb']} GB total / {x['in_gpu_vram_gb']} GB in VRAM, context {x['context_length']}"
                      for x in env["memory"]) + " |",
                  f"| Eval run at | {env['timestamp_utc']} |", ""]
        lines += ["## Four ask-mode tests", "",
                  "| Test | Question | Retrieval found expected | Citation check | Auto verdict | Time (s) | Human assessment |",
                  "|---|---|---|---|---|---:|---|"]
        for c in cards:
            r = load(c)
            a = r["auto_checks"]
            lines.append(f"| [{r['test']['id']}](ask/{c.stem}.md) | {r['test']['question']} | "
                         f"{a['retrieval_found_expected']} | {a['citation_status']} | "
                         f"{'PASS' if a['passes'] else 'FAIL'} | {r['timing']['wall_seconds']} | "
                         f"{str(r['human_assessment'])[:80]} |")
        lines.append("")

    ingests = sorted((EVID / "ingest").glob("ingest-*.json"))
    if ingests:
        lines += ["## Ingestion runs", "", "| Run | Sources | Pages before → after | Created | Model calls | Time (s) | Offline |",
                  "|---|---|---|---|---:|---:|---|"]
        for p in ingests:
            r = load(p)
            lines.append(f"| `{p.stem}` | {', '.join(s['id'] for s in r['sources'])} | {r['pages_before']} → {r['pages_after']} | "
                         f"{len(r['created'])} | {len(r['calls'])} | {r['seconds']} | "
                         f"{not r['environment']['internet_reachable']} |")
        lines.append("")

    chats = sorted((EVID / "chat").glob("*.json"))
    if chats:
        lines += ["## Chat sessions", ""]
        for p in chats:
            r = load(p)
            lines.append(f"- [{p.stem}](chat/{p.stem}.md): {len(r['turns'])} turns; retrieved notes on "
                         f"{sum(t['decision']['retrieve'] for t in r['turns'])} of them; "
                         f"offline={not r['environment']['internet_reachable']}")
        lines.append("")

    out = EVID / "SUMMARY.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
